config/routes.rb
Rails.application.routes.draw do

  get 'tee/show'
  get 'search/index'

  root        'categories#show', :id => 'best-sellers'
  get         'about'   =>  'static_pages#about'
  resources   :categories,  only: [:show], :path => '/'

end

app/models/category.rb
class Category < ActiveRecord::Base
	def to_param
		url
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
require 'open-uri'

class CategoriesController < ApplicationController
  include ApplicationHelper
  def show
    @categories = Category.all
  	@category = Category.find_by_url(id_params[:id])
  	url = @category.url
  	if url == "best-sellers"
  		url += ".cfm"
		end
    @all_tees = get_all_tees("http://www.sunfrogshirts.com/" + url)
  end

  private
  	def id_params
  		params.permit(:id)
		end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include ApplicationHelper
  def index
  	@categories = Category.all
  	@search_query = search_params[:query]
    @all_tees = get_all_tees("http://www.sunfrogshirts.com/search/index.cfm?SEARCH=" + @search_query)
  end

  private
  	def search_params
  		params.permit(:query)
		end
end

app/controllers/static_pages_controller.rb
require 'open-uri'

class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/tee_controller.rb
require 'open-uri'

class TeeController < ApplicationController
  def show
  	tee_url = params[:name]
  	html_content = open("http://www.sunfrogshirts.com/" + tee_url)
  	doc = Nokogiri::HTML(html_content)

  	tee_name_css = '#col2 h1'
  	@tee_name = doc.css(tee_name_css).text

  	
  end
end

app/helpers/application_helper.rb
require 'open-uri'

module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Tee Shop"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def get_all_tees(url)
		html_content = open(url)
  	doc = Nokogiri::HTML(html_content)

    tee_css_selector = '.productIcon'

		all_tees = []
		tee_imgs = doc.css(tee_css_selector + ' .frame img')
		tee_imgs.each do |tee_img|
			all_tees << {src: tee_img.attr("data-original")}
		end

    tee_names = doc.css(tee_css_selector + ' .product-Title')
    for i in 0..all_tees.length-1
      all_tees[i][:name] = tee_names[i].text
    end

    tee_prices = doc.css(tee_css_selector + ' .product-price')
    for i in 0..all_tees.length-1
      all_tees[i][:price] = tee_prices[i].text
    end

    tee_url = doc.css(' .frame a')
    for i in 0..all_tees.length-1
      all_tees[i][:link] = tee_url[i].attr('href')
    end

    all_tees
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tee_helper.rb
module TeeHelper
end

app/views/categories/show.html.erb
<%= provide(:title, @category.name) %>
<%= provide(:css_file, (stylesheet_link_tag 'categories', :media => "all")) %>
<%= provide(:js_file, (javascript_include_tag 'categories')) %>

<div id="category-page">
	<div class="row">
		<div class="large-2 columns">
			<%= render 'partials/sidebar' %>
		</div>
		<div class="large-10 columns">
			<p class="font-bold fs20"><%= @category_selected_name %></p>
			<ul class="large-block-grid-4">
				<% @all_tees.each do |tee| %>
					<li>
						<a href="<%= tee_show_path(name: tee[:link]) %>">
						<div class="product">
							<div class="frame">
								<img class="lazy" data-original="<%= tee[:src] %>" width="200" height="300">
							</div>
							<div class="product-info">
								<h1 class="font-medium fs15">
									<span><%= tee[:name] %></span><br/>
									<span><%= tee[:price] %></span>
								</h1>
							</div>
						</div>
						</a>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'partials/header' %>

    <%= yield %>

    <%= content_for?(:css_file) ? yield(:css_file) : "" %>
    <%= content_for?(:js_file) ? yield(:js_file) : "" %>
  </body>

  <%= javascript_include_tag "jquery.lazyload.js" %>
  <%= javascript_include_tag "_header" %>
</html>

app/views/partials/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<%= image_tag 'logo.png' %>
			<h1 class="font-bold"><a href="/">Tee Shop</a></h1>
		</li>
	</ul>

	<section class="top-bar-section">
		<ul class="right">
			<li class="has-form">
				<form id="search-form" action=<%= search_index_path %> method="GET">
					<input type="text" name="query"/>
				</form>
			</li>
			<li>
				<%= button_tag "Search", id: "search-button" %>
			</li>
		</ul>
	</section>
</nav>

app/views/partials/_sidebar.html.erb
<p class="font-bold fs20 no-mgbot">Categories</p>
	<ul class="side-nav">
		<% @categories.each do |category| %>
			<li <%=("class=\"active\"").html_safe if @category && @category.name == category.name %>><a href="<%= category_path(category) %>"><%= category.name %></a></li>
		<% end %>
	</ul>

app/views/search/index.html.erb
<%= provide(:title, 'Search') %>
<%= provide(:css_file, (stylesheet_link_tag 'categories', :media => "all")) %>
<%= provide(:js_file, (javascript_include_tag 'categories')) %>

<div id="category-page">
	<div class="row">
		<div class="large-2 columns">
			<%= render 'partials/sidebar' %>
		</div>
		<div class="large-10 columns">
			<p class="font-bold fs20">Search results for: "<%= @search_query%>"</p>
			<ul class="large-block-grid-4">
				<% @all_tees.each do |tee| %>
					<li>
						
						<div class="product">
							<div class="frame">
								<img class="lazy" data-original="<%= tee[:src] %>" width="200" height="300">
							</div>
							<div class="product-info">
								<h1 class="font-medium fs15">
									<span><%= tee[:name] %></span><br/>
									<span><%= tee[:price] %></span>
								</h1>
							</div>
						</div>	
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<%= provide(:title, 'Home') %>
<%= provide(:css_file, (stylesheet_link_tag 'static_pages_home', :media => "all")) %>
<%= provide(:js_file, (javascript_include_tag 'static_pages_home')) %>

<div id="homepage">
	<div class="row">
		<div class="large-2 columns">
			<p class="font-bold fs20 no-mgbot">Categories</p>
			<ul class="side-nav">
				<% @categories_text.each do |category| %>
					<li <%=("class=\"active\"").html_safe if @category_selected_name == category.titleize %>><a href="<%= category_name_to_url(category) %>"><%= category %></a></li>
				<% end %>
			</ul>
		</div>
		<div class="large-10 columns">
			<p class="font-bold fs20"><%= @category_selected_name %></p>
			<ul class="large-block-grid-4">
				<% @all_tees.each do |tee| %>
					<li>
						<div class="product">
							<div class="frame">
								<img class="lazy" data-original="<%= tee[:src] %>" width="200" height="300">
							</div>
							<div class="product-info">
								<h1 class="font-medium fs15">
									<span><%= tee[:name] %></span><br/>
									<span><%= tee[:price] %></span>
								</h1>
							</div>
						</div>	
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/tee/show.html.erb
<%= provide(:title, @tee_name) %>
<%= provide(:css_file, (stylesheet_link_tag 'tee', :media => "all")) %>
<%= provide(:js_file, (javascript_include_tag 'tee')) %>

<div id="tee-page">
	<div class="row">
		<div class="large-2 columns">
			<%= render 'partials/sidebar' %>
		</div>
		<div class="large-10 columns">
			<p class="font-bold fs20"><%= @tee_name %></p>
		</div>
	</div>
</div>